services:
  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: joystick_junction_dev
    ports:
      - 5432:5432
