services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: joystick_junction_development
    ports:
      - 5432:5432

volumes:
  postgres_volume:
